[package]
name = "srambist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_chacha = { version = "0.3.1", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
