[package]
name = "tsi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4"
clap = { version = "4", features = ["derive"] }
clap-num = "1"
hex = "0.4"

[[bin]]
name = "uarttsi"
